name: push-documentation

on:
  pull_request:
    branches-ignore: [documentation, gh-pages]
  push:
    branches: [master]
    tags: ['v*']
    paths:
      - 'docs/**'

jobs:
  push-to-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SERVER_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Release API documentation to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: irrelevant
        run: |
          git config --global user.email "irrelevant@completely.irrelevant"
          git config --global user.name "irrelevant"
          cd ..
          git clone --depth 1 -b documentation git@github.com:SAP/cloud-sdk.git documentation
          pwd
          cd cloud-sdk
          pwd
          cd ../documentation
          pwd
